# Generated by Django 2.1.5 on 2019-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=65)),
                ('email', models.EmailField(max_length=65, unique=True)),
            ],
        ),
    ]
