# Generated by Django 2.1.2 on 2019-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='contact_no',
            field=models.CharField(default='0000000000', max_length=65, unique=True),
        ),
    ]
