# Generated by Django 2.1.2 on 2019-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_survey_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='contact_no',
            field=models.CharField(default='0', max_length=65, unique=True),
        ),
    ]
