# Generated by Django 2.1.2 on 2019-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_auto_20190203_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='survey',
            name='contact_No',
            field=models.CharField(default='', max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='address',
            field=models.CharField(max_length=256),
        ),
    ]
